#!/bin/sh

if [ "${REQUEST_METHOD:-}" != "POST" ]; then
    printf 'Status: 405 Method Not Allowed\r\nAllow: POST\r\nContent-Type: text/plain; charset=utf-8\r\n\r\nMethod Not Allowed\n'
    exit 0
fi

printf 'Content-Type: text/plain; charset=utf-8\r\n\r\n'
/home/pi/PiCanLog/picanlog status 2>&1
